// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arhprpfmdxsqvzpxrbqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyaHBycGZtZHhzcXZ6cHhyYnFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4Nzc1NDUsImV4cCI6MjA1NzQ1MzU0NX0.oDsd6rv8HBgBLEFg5AIu8sauWZu3rWyXq18t9ew8vBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);