name: Test and Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run build test
        run: npm run build
        
      - name: Run linting (if available)
        run: npm run lint --if-present
        continue-on-error: true
        
      - name: Check build artifacts
        run: ls -la dist/
        
      - name: Build size check
        run: du -sh dist/
        
  # Vercel will handle deployments automatically via GitHub integration
  # No need for manual deployment steps here 